### YamlMime:ManagedReference
items:
- uid: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig
  commentId: T:VMS.TPS.Common.Model.Types.DoseValueDisplayConfig
  id: DoseValueDisplayConfig
  parent: VMS.TPS.Common.Model.Types
  children:
  - VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.#ctor
  - VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.Decimals(VMS.TPS.Common.Model.Types.DoseValue.DoseUnit)
  - VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.DisplaySettings
  langs:
  - csharp
  - vb
  name: DoseValueDisplayConfig
  nameWithType: DoseValueDisplayConfig
  fullName: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig
  type: Class
  assemblies:
  - VMS.TPS.Common.Model.Types
  namespace: VMS.TPS.Common.Model.Types
  summary: >-
    Configure the settings related to the dose value display for the application.

    Defaults to the same settings as Eclipse.
  example: []
  syntax:
    content: public class DoseValueDisplayConfig
    content.vb: Public Class DoseValueDisplayConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
- uid: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.Decimals(VMS.TPS.Common.Model.Types.DoseValue.DoseUnit)
  commentId: M:VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.Decimals(VMS.TPS.Common.Model.Types.DoseValue.DoseUnit)
  id: Decimals(VMS.TPS.Common.Model.Types.DoseValue.DoseUnit)
  parent: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig
  langs:
  - csharp
  - vb
  name: Decimals(DoseUnit)
  nameWithType: DoseValueDisplayConfig.Decimals(DoseValue.DoseUnit)
  fullName: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.Decimals(VMS.TPS.Common.Model.Types.DoseValue.DoseUnit)
  type: Method
  assemblies:
  - VMS.TPS.Common.Model.Types
  namespace: VMS.TPS.Common.Model.Types
  summary: Get number of decimals to user for dosevalue of the defined dose unit
  example: []
  syntax:
    content: public static int Decimals(DoseValue.DoseUnit unit)
    parameters:
    - id: unit
      type: VMS.TPS.Common.Model.Types.DoseValue.DoseUnit
      description: DoseUnit for which the number of decimals is requested.
    return:
      type: System.Int32
      description: Configured number of decimals to use.
    content.vb: Public Shared Function Decimals(unit As DoseValue.DoseUnit) As Integer
  overload: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.Decimals*
- uid: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.#ctor
  commentId: M:VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.#ctor
  id: '#ctor'
  parent: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig
  langs:
  - csharp
  - vb
  name: DoseValueDisplayConfig()
  nameWithType: DoseValueDisplayConfig.DoseValueDisplayConfig()
  fullName: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.DoseValueDisplayConfig()
  type: Constructor
  assemblies:
  - VMS.TPS.Common.Model.Types
  namespace: VMS.TPS.Common.Model.Types
  syntax:
    content: public DoseValueDisplayConfig()
    content.vb: Public Sub New()
  overload: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.#ctor*
  nameWithType.vb: DoseValueDisplayConfig.New()
  fullName.vb: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.New()
  name.vb: New()
- uid: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.DisplaySettings
  commentId: P:VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.DisplaySettings
  id: DisplaySettings
  parent: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig
  langs:
  - csharp
  - vb
  name: DisplaySettings
  nameWithType: DoseValueDisplayConfig.DisplaySettings
  fullName: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.DisplaySettings
  type: Property
  assemblies:
  - VMS.TPS.Common.Model.Types
  namespace: VMS.TPS.Common.Model.Types
  summary: >-
    Get and set current dosevalue display settings.

    Set settings controller to null reverts to default display settings.
  example: []
  syntax:
    content: public static IDoseValueDisplaySettings DisplaySettings { get; set; }
    parameters: []
    return:
      type: VMS.TPS.Common.Model.Types.IDoseValueDisplaySettings
    content.vb: Public Shared Property DisplaySettings As IDoseValueDisplaySettings
  overload: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.DisplaySettings*
references:
- uid: VMS.TPS.Common.Model.Types
  commentId: N:VMS.TPS.Common.Model.Types
  isExternal: true
  href: VMS.html
  name: VMS.TPS.Common.Model.Types
  nameWithType: VMS.TPS.Common.Model.Types
  fullName: VMS.TPS.Common.Model.Types
  spec.csharp:
  - uid: VMS
    name: VMS
    isExternal: true
    href: VMS.html
  - name: .
  - uid: VMS.TPS
    name: TPS
    isExternal: true
    href: VMS.TPS.html
  - name: .
  - uid: VMS.TPS.Common
    name: Common
    isExternal: true
    href: VMS.TPS.Common.html
  - name: .
  - uid: VMS.TPS.Common.Model
    name: Model
    isExternal: true
    href: VMS.TPS.Common.Model.html
  - name: .
  - uid: VMS.TPS.Common.Model.Types
    name: Types
    isExternal: true
    href: VMS.TPS.Common.Model.Types.html
  spec.vb:
  - uid: VMS
    name: VMS
    isExternal: true
    href: VMS.html
  - name: .
  - uid: VMS.TPS
    name: TPS
    isExternal: true
    href: VMS.TPS.html
  - name: .
  - uid: VMS.TPS.Common
    name: Common
    isExternal: true
    href: VMS.TPS.Common.html
  - name: .
  - uid: VMS.TPS.Common.Model
    name: Model
    isExternal: true
    href: VMS.TPS.Common.Model.html
  - name: .
  - uid: VMS.TPS.Common.Model.Types
    name: Types
    isExternal: true
    href: VMS.TPS.Common.Model.Types.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.Decimals*
  commentId: Overload:VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.Decimals
  isExternal: true
  href: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.html#VMS_TPS_Common_Model_Types_DoseValueDisplayConfig_Decimals_VMS_TPS_Common_Model_Types_DoseValue_DoseUnit_
  name: Decimals
  nameWithType: DoseValueDisplayConfig.Decimals
  fullName: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.Decimals
- uid: VMS.TPS.Common.Model.Types.DoseValue.DoseUnit
  commentId: T:VMS.TPS.Common.Model.Types.DoseValue.DoseUnit
  parent: VMS.TPS.Common.Model.Types
  isExternal: true
  href: VMS.TPS.Common.Model.Types.DoseValue.html
  name: DoseValue.DoseUnit
  nameWithType: DoseValue.DoseUnit
  fullName: VMS.TPS.Common.Model.Types.DoseValue.DoseUnit
  spec.csharp:
  - uid: VMS.TPS.Common.Model.Types.DoseValue
    name: DoseValue
    isExternal: true
    href: VMS.TPS.Common.Model.Types.DoseValue.html
  - name: .
  - uid: VMS.TPS.Common.Model.Types.DoseValue.DoseUnit
    name: DoseUnit
    isExternal: true
    href: VMS.TPS.Common.Model.Types.DoseValue.DoseUnit.html
  spec.vb:
  - uid: VMS.TPS.Common.Model.Types.DoseValue
    name: DoseValue
    isExternal: true
    href: VMS.TPS.Common.Model.Types.DoseValue.html
  - name: .
  - uid: VMS.TPS.Common.Model.Types.DoseValue.DoseUnit
    name: DoseUnit
    isExternal: true
    href: VMS.TPS.Common.Model.Types.DoseValue.DoseUnit.html
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.#ctor*
  commentId: Overload:VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.#ctor
  isExternal: true
  href: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.html#VMS_TPS_Common_Model_Types_DoseValueDisplayConfig__ctor
  name: DoseValueDisplayConfig
  nameWithType: DoseValueDisplayConfig.DoseValueDisplayConfig
  fullName: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.DoseValueDisplayConfig
  nameWithType.vb: DoseValueDisplayConfig.New
  fullName.vb: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.New
  name.vb: New
- uid: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.DisplaySettings*
  commentId: Overload:VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.DisplaySettings
  isExternal: true
  href: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.html#VMS_TPS_Common_Model_Types_DoseValueDisplayConfig_DisplaySettings
  name: DisplaySettings
  nameWithType: DoseValueDisplayConfig.DisplaySettings
  fullName: VMS.TPS.Common.Model.Types.DoseValueDisplayConfig.DisplaySettings
- uid: VMS.TPS.Common.Model.Types.IDoseValueDisplaySettings
  commentId: T:VMS.TPS.Common.Model.Types.IDoseValueDisplaySettings
  parent: VMS.TPS.Common.Model.Types
  isExternal: true
  href: VMS.TPS.Common.Model.Types.IDoseValueDisplaySettings.html
  name: IDoseValueDisplaySettings
  nameWithType: IDoseValueDisplaySettings
  fullName: VMS.TPS.Common.Model.Types.IDoseValueDisplaySettings
