# This workflow will build a .NET project using GitHub Actions
# For more information see: https://docs.github.com/en/actions/guides/building-and-testing-net

name: Dicom Example Build
permissions:
  checks: write
  pull-requests: write
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore dicom-example.sln

    - name: Build
      run: dotnet build dicom-example.sln --configuration Release --no-restore

    - name: Test
      run: |
        dotnet test dicom-example.sln --logger "trx;LogFileName=test-results.trx" --results-directory ./TestResults
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    - name: Publish Test Results to Summary
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results Report
        path: ./TestResults/*.trx
        reporter: dotnet-trx
`
  publish-Esavi-dll:
    name: Publish EsaviDLL Artifact
    needs: [ build ]
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build ./src/Esavi/Esavi.csproj --configuration Release  --verbosity quiet 

      - name: Install Nerdbank.GitVersioning
        run: dotnet tool restore || dotnet tool install --local nbgv

      - name: Set version from Git
        run: dotnet nbgv cloud

      - name: Download Esavi DLL Artifact
        uses: actions/download-artifact@v4
        with:
          name: Esavi-*

      - name: Rename Esavi DLL with version and commit
        uses: ./.github/actions/upload-dll
        with:
          project: Esavi
